preset: symfony

enabled:
  - align_double_arrow
  - concat_with_spaces
  - short_array_syntax
  - ordered_use
  - strict

disabled:
  - blank_line_before_break
  - blank_line_before_continue
  - blank_line_before_throw
  - blank_line_before_try
  - concat_without_spaces
  - method_argument_space
  - pre_increment
  - unalign_double_arrow
  - unalign_equals
  - yoda_style
  - property_separation
  - const_separation

finder:
  name:
    - "*.php"
    - ".php_cs"
    - "build-manual"
    - "build-phar"
