#!/usr/bin/env php
<?php

function compile($in, $out)
{
    $cmd = sprintf("gcc -lbsd -o %s %s", escapeshellarg($out), escapeshellarg($in));
    system($cmd, $retcode);
    if (0 != $retcode) {
        echo "Could not compile $out from $in\n";
        exit(1);
    }
}
function execute($exe, $arg) {
    $arg = escapeshellarg($arg);
    $cmd = sprintf('%s/%s %s', __DIR__, $exe, $arg);
    $result = shell_exec($cmd);
    if (!$result) {
        echo "ERROR: Command $cmd did not return any result.\n";
    }
    return $result;
}

foreach(array('vis', 'unvis') as $exe) {
    $exe_path = __DIR__."/$exe";
    $src_path = __DIR__."/$exe.c";
    if (!file_exists($exe_path)) {
        echo "$exe executable not found, trying to compile...\n";
        compile($src_path, $exe_path);
    }
    if (!is_executable($exe_path)) {
        chmod($exe_path, 0755);
    }
}

$raw_strings = array_map('chr', range(0, 20));
$raw_strings = array_merge($raw_strings, array(
    "éèàœ€æâêþÿûîœôäßë",
    "‘’ðüïŀö«»© ↓",
    "¬¿×÷¡ùÆÂ¢ÊÞŸÛÎŒÔ",
    "°ØÄ„Ë‚¥ÐÜÏĿÖ“”®←↑→…⋅§",
    "foo bar",
    "foo\nbar",
    "hey\xa0yao",
    '$foo = "bar";'
));

$fixtures = array();

foreach ($raw_strings as $raw_string) {
    $encoded = execute('vis', $raw_string);
    if (null === $encoded) continue;
    $decoded = execute('unvis', $encoded);
    if (null === $decoded) continue;
    $fixtures[] = array($encoded, $decoded);
}

$content = <<<'EOS'
<?php
// This file has been generated by psysh/test/tools/gen-unvis-fixtures.php

return %s;

?>
EOS;

file_put_contents(
    __DIR__.'/../fixtures/unvis_fixtures.php',
    sprintf($content, var_export($fixtures, true))
);
